// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("ipdiscovery")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/ipdiscoveryreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
