// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: agent_contact_exporter.proto

package protocol

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentContact_SendTraceIDs_FullMethodName = "/agentcontactexporter.AgentContact/SendTraceIDs"
)

// AgentContactClient is the client API for AgentContact service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentContact service defines the gRPC interface for agent contact protocol
type AgentContactClient interface {
	// SendTraceIDs sends a list of trace IDs to the remote collector
	SendTraceIDs(ctx context.Context, in *TraceIDRequest, opts ...grpc.CallOption) (*TraceIDResponse, error)
}

type agentContactClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentContactClient(cc grpc.ClientConnInterface) AgentContactClient {
	return &agentContactClient{cc}
}

func (c *agentContactClient) SendTraceIDs(ctx context.Context, in *TraceIDRequest, opts ...grpc.CallOption) (*TraceIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceIDResponse)
	err := c.cc.Invoke(ctx, AgentContact_SendTraceIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentContactServer is the server API for AgentContact service.
// All implementations must embed UnimplementedAgentContactServer
// for forward compatibility.
//
// AgentContact service defines the gRPC interface for agent contact protocol
type AgentContactServer interface {
	// SendTraceIDs sends a list of trace IDs to the remote collector
	SendTraceIDs(context.Context, *TraceIDRequest) (*TraceIDResponse, error)
	mustEmbedUnimplementedAgentContactServer()
}

// UnimplementedAgentContactServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentContactServer struct{}

func (UnimplementedAgentContactServer) SendTraceIDs(context.Context, *TraceIDRequest) (*TraceIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTraceIDs not implemented")
}
func (UnimplementedAgentContactServer) mustEmbedUnimplementedAgentContactServer() {}
func (UnimplementedAgentContactServer) testEmbeddedByValue()                      {}

// UnsafeAgentContactServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentContactServer will
// result in compilation errors.
type UnsafeAgentContactServer interface {
	mustEmbedUnimplementedAgentContactServer()
}

func RegisterAgentContactServer(s grpc.ServiceRegistrar, srv AgentContactServer) {
	// If the following call pancis, it indicates UnimplementedAgentContactServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentContact_ServiceDesc, srv)
}

func _AgentContact_SendTraceIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentContactServer).SendTraceIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentContact_SendTraceIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentContactServer).SendTraceIDs(ctx, req.(*TraceIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentContact_ServiceDesc is the grpc.ServiceDesc for AgentContact service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentContact_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentcontactexporter.AgentContact",
	HandlerType: (*AgentContactServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTraceIDs",
			Handler:    _AgentContact_SendTraceIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_contact_exporter.proto",
}
