// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: agent_contact.proto

package protocol

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TraceIDRequest contains a list of trace IDs and span IDs to be processed
type TraceIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceIds      []string               `protobuf:"bytes,1,rep,name=trace_ids,json=traceIds,proto3" json:"trace_ids,omitempty"`
	SpanIds       []string               `protobuf:"bytes,2,rep,name=span_ids,json=spanIds,proto3" json:"span_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceIDRequest) Reset() {
	*x = TraceIDRequest{}
	mi := &file_agent_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceIDRequest) ProtoMessage() {}

func (x *TraceIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceIDRequest.ProtoReflect.Descriptor instead.
func (*TraceIDRequest) Descriptor() ([]byte, []int) {
	return file_agent_contact_proto_rawDescGZIP(), []int{0}
}

func (x *TraceIDRequest) GetTraceIds() []string {
	if x != nil {
		return x.TraceIds
	}
	return nil
}

func (x *TraceIDRequest) GetSpanIds() []string {
	if x != nil {
		return x.SpanIds
	}
	return nil
}

// TraceIDResponse contains the acknowledgment from the remote collector
type TraceIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceIDResponse) Reset() {
	*x = TraceIDResponse{}
	mi := &file_agent_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceIDResponse) ProtoMessage() {}

func (x *TraceIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceIDResponse.ProtoReflect.Descriptor instead.
func (*TraceIDResponse) Descriptor() ([]byte, []int) {
	return file_agent_contact_proto_rawDescGZIP(), []int{1}
}

func (x *TraceIDResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_agent_contact_proto protoreflect.FileDescriptor

const file_agent_contact_proto_rawDesc = "" +
	"\n" +
	"\x13agent_contact.proto\x12\fagentcontact\"H\n" +
	"\x0eTraceIDRequest\x12\x1b\n" +
	"\ttrace_ids\x18\x01 \x03(\tR\btraceIds\x12\x19\n" +
	"\bspan_ids\x18\x02 \x03(\tR\aspanIds\"#\n" +
	"\x0fTraceIDResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack2[\n" +
	"\fAgentContact\x12K\n" +
	"\fSendTraceIDs\x12\x1c.agentcontact.TraceIDRequest\x1a\x1d.agentcontact.TraceIDResponseBaZ_github.com/open-telemetry/opentelemetry-collector-contrib/internal/common/agentcontact/protocolb\x06proto3"

var (
	file_agent_contact_proto_rawDescOnce sync.Once
	file_agent_contact_proto_rawDescData []byte
)

func file_agent_contact_proto_rawDescGZIP() []byte {
	file_agent_contact_proto_rawDescOnce.Do(func() {
		file_agent_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_contact_proto_rawDesc), len(file_agent_contact_proto_rawDesc)))
	})
	return file_agent_contact_proto_rawDescData
}

var file_agent_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_contact_proto_goTypes = []any{
	(*TraceIDRequest)(nil),  // 0: agentcontact.TraceIDRequest
	(*TraceIDResponse)(nil), // 1: agentcontact.TraceIDResponse
}
var file_agent_contact_proto_depIdxs = []int32{
	0, // 0: agentcontact.AgentContact.SendTraceIDs:input_type -> agentcontact.TraceIDRequest
	1, // 1: agentcontact.AgentContact.SendTraceIDs:output_type -> agentcontact.TraceIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_contact_proto_init() }
func file_agent_contact_proto_init() {
	if File_agent_contact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_contact_proto_rawDesc), len(file_agent_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_contact_proto_goTypes,
		DependencyIndexes: file_agent_contact_proto_depIdxs,
		MessageInfos:      file_agent_contact_proto_msgTypes,
	}.Build()
	File_agent_contact_proto = out.File
	file_agent_contact_proto_goTypes = nil
	file_agent_contact_proto_depIdxs = nil
}
