// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("statisticsaggregation")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/statisticsaggregationprocessor"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
