// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("priority")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/priorityprocessor"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
